// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import HelloController from "./hello_controller"

import LocationController from "./location_controller"

import ReservistLocationController from "./reservist_location_controller"

application.register("hello", HelloController)
application.register("location", LocationController)
application.register("reservist-location", ReservistLocationController)